# Generated by Django 5.1.3 on 2024-11-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='place',
            field=models.CharField(max_length=50),
        ),
    ]
